services:
  mongo:
    image: mongo:5.0.9
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: _@QffsDh14Q
      MONGO_INITDB_DATABASE: myadminpanel
    ports:
      - "27017:27017"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: api
      dockerfile: ./DockerFile
    container_name: api
    ports:
      - "5001:5001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/myadminpanel
    networks:
      - app-network
    depends_on:
      mongo:
        condition: service_healthy


configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  app-network:
    driver: bridge