services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: _@QffsDh14Q
      MONGO_INITDB_DATABASE: myadminpanel
    ports:
      - "27017:27017"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build:
      context: api
      dockerfile: ./DockerFile
    container_name: api
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

  admin-panel:
    build:
      context: admin-panel
      dockerfile: ./DockerFile
    container_name: admin-panel
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      mongo:
        condition: service_healthy
    restart: always

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  app-network:
    driver: bridge